# Generated by Django 5.2.17 on 2026-08-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_estandar', models.CharField(help_text='Pregunta base que será vectorizada para la comparación de similitud.', max_length=255, unique=True)),
                ('respuesta_aprobada', models.TextField(help_text='Respuesta técnica oficial que se enviará al usuario (evita el uso de la GPU).')),
                ('frecuencia_uso', models.PositiveIntegerField(default=0, help_text='Contador estadístico de cuántas veces el sistema ha interceptado y reciclado esta respuesta.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro de la FAQ.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación de la respuesta.')),
            ],
            options={
                'verbose_name': 'Respuesta Frecuente',
                'verbose_name_plural': 'Respuestas Frecuentes',
                'ordering': ['-frecuencia_uso'],
            },
        ),
    ]
