# Generated by Django 5.2.17 on 2026-08-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satelite_telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(help_text='Nombre original del documento (ej. NCh2485_2000.pdf).', max_length=255)),
                ('archivo', models.FileField(help_text='Ruta física del archivo almacenado temporalmente en el servidor.', upload_to='documentos_pendientes/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Ingesta'), ('PROCESANDO', 'Vectorizando en Qdrant...'), ('COMPLETADO', 'Ingesta Exitosa'), ('ERROR', 'Error en Procesamiento')], default='PENDIENTE', help_text='Fase actual del documento en el pipeline de IA.', max_length=15)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, help_text='Momento exacto en que el usuario o administrador subió el PDF.')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, help_text='Marca de tiempo en la que el Satélite Nocturno finalizó la vectorización.', null=True)),
            ],
            options={
                'verbose_name': 'Documento Pendiente',
                'verbose_name_plural': 'Documentos Pendientes',
                'ordering': ['fecha_subida'],
            },
        ),
    ]
